channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
- pip
- faiss-cpu=1.8.0
- pip:
  - duckduckgo_search==5.3.1
  - beautifulsoup4==4.12.3
  - langchain==0.1.16
  - unstructured==0.11.8
  - rank_bm25==0.2.2
  - sentence-transformers==2.6.1
