channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
- pip
- faiss-cpu=1.8.0
- pip:
  - duckduckgo_search==6.3.1
  - beautifulsoup4==4.12.3
  - unstructured==0.15.13
  - rank_bm25==0.2.2
  - sentence-transformers==3.0.1
  - optimum==1.23.2
  - Brotli==1.1.0
